### ISSUE TITLE
Some problems at the beginning of the yml file

### ISSUE THREAD

**Issue by kaixuncao** [BigDataBiology/SantosJunior_Torres_2024_AMPSphere_v1#4]
Hello!
       I'm a bit confused by the “file:///home/celio/Downloads/LinuxArtifacts/packages” at the beginning of the yml file, and I was not able to find out from you what this file is? I couldn't find your description of what this file is and what's in this folder, could you tell me more details, this PWD is a bit too localized, thanks a lot :)

**Comment by celiosantosjr** [comment]
Hi, 

Thanks for the issue. These specific files should not be needed and would refer to the original system were the analysis was run. Therefore, they were eliminated from the `.yml` file without major consequences. It should work fine now.
